version: '3.8'
services:
  webserver:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    tmpfs: /etc/nginx/cache
    volumes:
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./usr/share/nginx/json:/usr/share/nginx/json
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    working_dir: /usr/share/nginx/html