version: '3.8'
services:
  webserver:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    healthcheck:
      test: ["CMD", "curl", "http://localhost/"]
      interval: 8s
      start_period: 4s
      retries: 2
    tmpfs: /etc/nginx/cache
    volumes:
      - ./usr/share/nginx/html:/usr/share/nginx/html
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    working_dir: /usr/share/nginx/html